/** Tool page meta: path, title, description. SEO/GEO-optimized, unique per page, ~50–60 char title, ~155 char description. */
export const TOOL_PAGES: { path: string; title: string; description: string }[] = [
  { path: '/word-unscrambler', title: 'Word Unscrambler', description: 'Unscramble up to 15 letters with filters and wildcards. Built for Scrabble, Wordle, and Words with Friends. No app required.' },
  { path: '/anagram-solver', title: 'Anagram Solver', description: 'Type your letters and see every anagram. Handy for puzzles and word games. Same dictionary as our main unscrambler.' },
  { path: '/wordle-solver', title: 'Wordle Solver', description: 'Use green, yellow, and gray clues to narrow down the answer. Get the best next 5-letter guess in seconds.' },
  { path: '/scrabble', title: 'Scrabble Word Finder', description: 'Enter your tiles and blanks. See high-scoring plays sorted by points. Uses a standard English word list.' },
  { path: '/words-with-friends', title: 'Words With Friends Cheat', description: 'Stuck on a rack? Enter your letters and get playable words. Sorted by score so you can pick the best move.' },
  { path: '/word-finder', title: 'Word Finder', description: 'One place to find words from your letters. Works for Scrabble, Wordle, crosswords, and any word game.' },
  { path: '/word-solver', title: 'Word Solver', description: 'Stuck on a word puzzle? Type your letters and optional pattern. We list every valid word that fits.' },
  { path: '/word-generator', title: 'Word Generator', description: 'Need a random word by length? Pick 2–10 letters and get valid words. Useful for games and brainstorming.' },
  { path: '/word-scramble', title: 'Word Scramble Solver', description: 'Jumbled letters from a puzzle or classroom game? Paste them here and get all possible words.' },
  { path: '/jumble-solver', title: 'Jumble Solver', description: 'Solve the daily Jumble. Enter the scrambled words and we show every anagram so you can find the answer.' },
  { path: '/boggle-solver', title: 'Boggle Solver', description: 'Enter your 16 letters in order (4×4). We list every word on the board. Great for checking or practice.' },
  { path: '/wordle', title: 'Wordle Helper', description: 'Tips and 5-letter word ideas for Wordle. Use with green and yellow clues to narrow down today’s answer.' },
  { path: '/wordscapes', title: 'Wordscapes Help', description: 'Stuck on a level? Enter the letters and we show valid words. No downloads, runs in your browser.' },
  { path: '/word-cookies', title: 'Word Cookies Answers', description: 'Enter the letters from your Word Cookies level. We list all valid words so you can finish the puzzle.' },
  { path: '/wordfeud', title: 'Wordfeud Helper', description: 'Enter your tiles and get high-scoring words. Same logic as our Scrabble finder, tuned for Wordfeud.' },
  { path: '/scrabble-go', title: 'Scrabble GO Helper', description: 'Type your rack and optional blanks. We show the best words by score. No account needed.' },
  { path: '/scrabble-cheat', title: 'Scrabble Cheat', description: 'Need a play from your tiles? Enter them here and see every valid word, sorted by Scrabble points.' },
  { path: '/hangman-solver', title: 'Hangman Solver', description: 'Know some letters? Use underscores for the rest (e.g. a__le). We list every word that matches.' },
  { path: '/letter-boxed-solver', title: 'Letter Boxed Solver', description: 'NYT Letter Boxed: enter the 12 letters by side. We suggest words that use all sides of the box.' },
  { path: '/text-twist', title: 'Text Twist Solver', description: 'Enter your Text Twist letters and get every word. Find the longest words and beat the round.' },
  { path: '/word-search-solver', title: 'Word Search Solver', description: 'Stuck on a word search? Enter the letters or paste the grid. We help you find the words.' },
  { path: '/descrambler', title: 'Word Descrambler', description: 'Type scrambled letters and get real words. No sign-up. Works for any word game or puzzle.' },
  { path: '/words-by-length', title: 'Words By Length', description: 'Browse the dictionary by letter count. Jump to 2-letter through 10-letter words. Links to unscramble and word finders.' },
  { path: '/words-start-with', title: 'Words Start With', description: 'Find words that start with a given letter. Choose by length or browse all. Handy for rhymes and word games.' },
  { path: '/words-ending-in', title: 'Words Ending In', description: 'Words that end with a specific letter. Browse by length or letter. Useful for rhyming and vocabulary.' },
  { path: '/words-with-letters', title: 'Words With Letters', description: 'Find words that contain a certain letter. Pick length and letter to see the full list. No app required.' },
];
