/** Tool page meta: path, title, description. Used to generate static pages. */
export const TOOL_PAGES: { path: string; title: string; description: string }[] = [
  { path: '/word-unscrambler', title: 'Word Unscrambler', description: 'Unscramble letters to words (up to 15 letters). Advanced filters and wildcards for Scrabble, Wordle, Words with Friends.' },
  { path: '/anagram-solver', title: 'Anagram Solver', description: 'Find all anagrams from your letters. Fast anagram solver for word games and puzzles.' },
  { path: '/wordle-solver', title: 'Wordle Solver', description: 'Solve Wordle with green, yellow, and gray clues. Get the best 5-letter word suggestions.' },
  { path: '/scrabble', title: 'Scrabble Word Finder', description: 'Scrabble word finder and cheat tool. Find high-scoring words from your tiles.' },
  { path: '/words-with-friends', title: 'Words With Friends Cheat', description: 'Words With Friends cheat tool. Find the best words from your letters.' },
  { path: '/word-finder', title: 'Word Finder', description: 'Word finder for Scrabble and Words with Friends. Enter letters and get valid words.' },
  { path: '/word-solver', title: 'Word Solver', description: 'Solve any word puzzle from your letters. Universal word solver for games and crosswords.' },
  { path: '/word-generator', title: 'Word Generator', description: 'Random word generator for games, writing, and brainstorming.' },
  { path: '/word-scramble', title: 'Word Scramble Solver', description: 'Solve word scramble puzzles. Unscramble scrambled words instantly.' },
  { path: '/jumble-solver', title: 'Jumble Solver', description: 'Solve daily Jumble word puzzles. Unscramble jumbled words and find answers.' },
  { path: '/boggle-solver', title: 'Boggle Solver', description: 'Find all words in your Boggle board. Enter 16 letters and get valid words.' },
  { path: '/wordle', title: 'Wordle Helper', description: 'Wordle helper with daily tips, strategy, and word suggestions.' },
  { path: '/wordscapes', title: 'Wordscapes Help', description: 'Wordscapes help with daily answers, tips, and word finder.' },
  { path: '/word-cookies', title: 'Word Cookies Answers', description: 'Word Cookies answers and word finder. Solve levels with our tool.' },
  { path: '/wordfeud', title: 'Wordfeud Helper', description: 'Wordfeud helper and word finder. Get high-scoring words for Wordfeud.' },
  { path: '/scrabble-go', title: 'Scrabble GO Helper', description: 'Scrabble GO helper to find high-scoring words from your letters.' },
  { path: '/scrabble-cheat', title: 'Scrabble Cheat', description: 'Scrabble cheat and word finder for high-scoring plays.' },
  { path: '/hangman-solver', title: 'Hangman Solver', description: 'Solve Hangman puzzles. Find words that match your pattern.' },
  { path: '/letter-boxed-solver', title: 'Letter Boxed Solver', description: 'NYT Letter Boxed solver. Find words that use all sides of the box.' },
  { path: '/text-twist', title: 'Text Twist Solver', description: 'Text Twist solver. Unscramble letters and find all words.' },
  { path: '/word-search-solver', title: 'Word Search Solver', description: 'Word search solver. Find words in your word search grid.' },
  { path: '/descrambler', title: 'Word Descrambler', description: 'Word descrambler tool. Unscramble letters into words fast.' },
  { path: '/words-by-length', title: 'Words By Length', description: 'Browse words by length. Find 2-letter to 10-letter words.' },
  { path: '/words-start-with', title: 'Words Start With', description: 'Find words that start with a specific letter or prefix.' },
  { path: '/words-ending-in', title: 'Words Ending In', description: 'Find words that end with a specific letter or suffix.' },
  { path: '/words-with-letters', title: 'Words With Letters', description: 'Find words that contain specific letters.' },
];
