// Utility functions for word manipulation and solving

export function unscrambleWord(letters: string): string[] {
  // This is a simplified example - in production, you'd use a dictionary API or database
  const mockWords = [
    "listen",
    "silent",
    "enlist",
    "tinsel",
    "hello",
    "world",
    "react",
    "next",
    "word",
    "game",
    "puzzle",
    "solver",
  ]

  const normalizedLetters = letters.toLowerCase().split("").sort().join("")

  return mockWords.filter((word) => {
    const wordLetters = word.split("").sort().join("")
    return wordLetters === normalizedLetters || word.includes(letters.toLowerCase())
  })
}

export function generateAnagrams(word: string): string[] {
  // Simplified anagram generation
  const mockAnagrams: Record<string, string[]> = {
    listen: ["silent", "enlist", "tinsel"],
    earth: ["heart", "hater"],
    night: ["thing"],
    stop: ["post", "pots", "spot", "tops"],
  }

  return mockAnagrams[word.toLowerCase()] || []
}

export function calculateScrabbleScore(word: string): number {
  const letterValues: Record<string, number> = {
    a: 1,
    b: 3,
    c: 3,
    d: 2,
    e: 1,
    f: 4,
    g: 2,
    h: 4,
    i: 1,
    j: 8,
    k: 5,
    l: 1,
    m: 3,
    n: 1,
    o: 1,
    p: 3,
    q: 10,
    r: 1,
    s: 1,
    t: 1,
    u: 1,
    v: 4,
    w: 4,
    x: 8,
    y: 4,
    z: 10,
  }

  return word
    .toLowerCase()
    .split("")
    .reduce((sum, letter) => sum + (letterValues[letter] || 0), 0)
}

export function filterWordsByLength(words: string[], length: number): string[] {
  return words.filter((word) => word.length === length)
}

export function getWordsByLength(length: number): string[] {
  // Sample words - in production, use a dictionary database
  const wordDatabase: Record<number, string[]> = {
    2: [
      "at",
      "be",
      "do",
      "go",
      "he",
      "if",
      "in",
      "is",
      "it",
      "me",
      "my",
      "no",
      "of",
      "on",
      "or",
      "so",
      "to",
      "up",
      "us",
      "we",
    ],
    3: [
      "ace",
      "act",
      "add",
      "age",
      "ago",
      "aid",
      "aim",
      "air",
      "all",
      "and",
      "ant",
      "any",
      "ape",
      "are",
      "ark",
      "arm",
      "art",
      "ask",
      "ate",
      "bad",
    ],
    4: [
      "able",
      "about",
      "acid",
      "aged",
      "also",
      "area",
      "army",
      "away",
      "baby",
      "back",
      "ball",
      "band",
      "bank",
      "base",
      "bear",
      "beat",
      "been",
      "best",
      "blue",
      "boat",
    ],
    5: [
      "about",
      "above",
      "abuse",
      "acids",
      "acres",
      "actor",
      "acute",
      "added",
      "admit",
      "adopt",
      "adult",
      "after",
      "again",
      "agent",
      "agree",
      "ahead",
      "alarm",
      "album",
      "alert",
      "alike",
    ],
    6: [
      "abroad",
      "accept",
      "access",
      "across",
      "acting",
      "action",
      "active",
      "actual",
      "adjust",
      "admire",
      "admit",
      "advice",
      "afford",
      "afraid",
      "agency",
      "agenda",
      "almost",
      "always",
      "amount",
      "animal",
    ],
    7: [
      "ability",
      "absence",
      "absolve",
      "academy",
      "account",
      "achieve",
      "acquire",
      "address",
      "advance",
      "adverse",
      "advised",
      "adviser",
      "against",
      "alcohol",
      "already",
      "amazing",
      "ancient",
      "another",
      "anxiety",
      "anxious",
    ],
    8: [
      "abandon",
      "absolute",
      "abstract",
      "academic",
      "accepted",
      "accident",
      "accompany",
      "accuracy",
      "accurate",
      "achieved",
      "activate",
      "actively",
      "activity",
      "actually",
      "addition",
      "adequate",
      "adjacent",
      "advanced",
      "advisory",
      "advocate",
    ],
    9: [
      "abandoned",
      "abilities",
      "abolition",
      "abortion",
      "absolutes",
      "absorbing",
      "abundance",
      "academic",
      "academics",
      "accepting",
      "accessory",
      "accession",
      "accidents",
      "accompany",
      "according",
      "accurately",
      "achieving",
      "acknowledge",
      "acquiring",
      "activated",
    ],
    10: [
      "abandoning",
      "abbreviate",
      "abdication",
      "aberration",
      "abilities",
      "abolishing",
      "abominable",
      "aboriginal",
      "absolutely",
      "absorption",
      "abstaining",
      "abstention",
      "abundantly",
      "academical",
      "accelerate",
      "acceptable",
      "acceptance",
      "accessible",
      "accidental",
      "accomplish",
    ],
  }

  return wordDatabase[length] || []
}
